services:
  uni-bot:
    build: .
    container_name: uni-bot

    # 1. This tells Docker to read your local .env file
    env_file:
      - .env
      
    # 2. Mount the state file so the bot remembers its Token ID
    volumes:
     - ./bot_state.json:/app/bot_state.json